<?php require_once __DIR__ . '/../includes/header.php'; require_once __DIR__ . '/../includes/csrf.php';
$user=current_user();
if($_SERVER['REQUEST_METHOD']==='POST'){
csrf_check();
$pdo->prepare('INSERT INTO lead_tasks(lead_id,title,assigned_user_id,due_date,priority,status,note,created_at) VALUES (?,?,?,?,?,?,?,NOW())')->execute([$_POST['lead_id']?:null,$_POST['title'],$_POST['assigned_user_id'],$_POST['due_date'],$_POST['priority'],$_POST['status'],$_POST['note']]);
header('Location: /tasks/index.php');exit;}
$where=$user['role']==='Staff'?' WHERE t.assigned_user_id='.(int)$user['id']:'';
$tasks=$pdo->query('SELECT t.*,l.full_name lead_name,u.full_name assignee FROM lead_tasks t LEFT JOIN leads l ON l.id=t.lead_id LEFT JOIN users u ON u.id=t.assigned_user_id'.$where.' ORDER BY t.due_date ASC')->fetchAll();
$leads=$pdo->query('SELECT id,full_name FROM leads WHERE deleted_at IS NULL ORDER BY full_name LIMIT 200')->fetchAll();
$users=$pdo->query("SELECT id,full_name FROM users WHERE status='Active' AND deleted_at IS NULL ORDER BY full_name")->fetchAll();
?><h3>Tasks & Reminders</h3><div class="card card-body mb-3"><form method="post" class="row g-2"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><div class="col-md-3"><input name="title" class="form-control" placeholder="Task title" required></div><div class="col-md-2"><select class="form-select" name="lead_id"><option value="">No lead</option><?php foreach($leads as $l):?><option value="<?= (int)$l['id'] ?>"><?= e($l['full_name']) ?></option><?php endforeach;?></select></div><div class="col-md-2"><select name="assigned_user_id" class="form-select"><?php foreach($users as $u):?><option value="<?= (int)$u['id'] ?>"><?= e($u['full_name']) ?></option><?php endforeach;?></select></div><div class="col-md-2"><input type="date" name="due_date" class="form-control" required></div><div class="col-md-1"><select class="form-select" name="priority"><option>Low</option><option selected>Medium</option><option>High</option></select></div><div class="col-md-1"><select class="form-select" name="status"><option>Pending</option><option>In Progress</option><option>Done</option><option>Cancelled</option></select></div><div class="col-md-1"><button class="btn btn-primary w-100">Add</button></div><div class="col-md-12"><input name="note" class="form-control" placeholder="Short note"></div></form></div>
<div class="table-responsive"><table class="table"><thead><tr><th>Title</th><th>Lead</th><th>Assignee</th><th>Due</th><th>Priority</th><th>Status</th></tr></thead><tbody><?php foreach($tasks as $t):?><tr><td><?= e($t['title']) ?></td><td><?= e($t['lead_name']) ?></td><td><?= e($t['assignee']) ?></td><td><?= e($t['due_date']) ?></td><td><span class="badge bg-<?= badge_class('priority',$t['priority']) ?>"><?= e($t['priority']) ?></span></td><td><span class="badge bg-<?= badge_class('task',$t['status']) ?>"><?= e($t['status']) ?></span></td></tr><?php endforeach;?></tbody></table></div>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
