<?php require_once __DIR__ . '/../includes/header.php';
$brandText = setting($pdo, 'report_branding', 'Professional Lead Report');
$companyName = setting($pdo, 'company_name', 'Startup Team');
$logo = setting($pdo, 'company_logo', '');
$from=$_GET['from']??date('Y-m-01');$to=$_GET['to']??date('Y-m-d');
$filterSql=' WHERE l.deleted_at IS NULL AND DATE(l.created_at) BETWEEN ? AND ? ';$params=[$from,$to];
foreach(['source','service_interest','stage','lead_type','city','assigned_user_id','priority'] as $f){if(!empty($_GET[$f])){$filterSql.=" AND l.$f=?";$params[]=$_GET[$f];}}
$tot=$pdo->prepare('SELECT COUNT(*) c FROM leads l'.$filterSql);$tot->execute($params);$total=$tot->fetch()['c'];
$won=$pdo->prepare("SELECT COUNT(*) c FROM leads l$filterSql AND l.stage='Closed Won'");$won->execute($params);$wonCount=$won->fetch()['c'];
$lost=$pdo->prepare("SELECT COUNT(*) c FROM leads l$filterSql AND l.stage IN ('Closed Lost','Not Interested')");$lost->execute($params);$lostCount=$lost->fetch()['c'];
$sourceData=$pdo->prepare('SELECT source,COUNT(*) c FROM leads l'.$filterSql.' GROUP BY source ORDER BY c DESC');$sourceData->execute($params);$sources=$sourceData->fetchAll();
$serviceData=$pdo->prepare('SELECT service_interest,COUNT(*) c FROM leads l'.$filterSql.' GROUP BY service_interest ORDER BY c DESC');$serviceData->execute($params);$services=$serviceData->fetchAll();
if(($_GET['export']??'')==='csv'){
 header('Content-Type:text/csv');header('Content-Disposition: attachment; filename="report.csv"');$o=fopen('php://output','w');fputcsv($o,['Metric','Value']);fputcsv($o,['Total Leads',$total]);fputcsv($o,['Closed Won',$wonCount]);fputcsv($o,['Closed Lost/Not Interested',$lostCount]);foreach($sources as $s)fputcsv($o,['Source: '.$s['source'],$s['c']]);foreach($services as $s)fputcsv($o,['Service: '.$s['service_interest'],$s['c']]);fclose($o);exit;
}
?><div class="card card-body mb-3"><div class="d-flex align-items-center gap-3"><?php if($logo): ?><img src="<?= e(url($logo)) ?>" style="height:40px"><?php endif; ?><div><h4 class="mb-0"><?= e($companyName) ?></h4><small class="text-muted"><?= e($brandText) ?></small></div></div></div><h3>Reports</h3><form class="row g-2 mb-3"><div class="col-md-2"><input type="date" class="form-control" name="from" value="<?= e($from) ?>"></div><div class="col-md-2"><input type="date" class="form-control" name="to" value="<?= e($to) ?>"></div><div class="col-md-2"><button class="btn btn-dark w-100">Apply Filter</button></div><div class="col-md-2"><a class="btn btn-outline-secondary w-100" href="?<?= e(http_build_query(array_merge($_GET,['export'=>'csv']))) ?>">Export CSV</a></div><div class="col-md-2"><a class="btn btn-outline-secondary w-100" href="#" onclick="window.print()">Print</a></div></form>
<div class="card card-body mb-3"><div class="row"><div class="col-md-4"><strong>Total Leads:</strong> <?= e((string)$total) ?></div><div class="col-md-4"><strong>Closed Won:</strong> <?= e((string)$wonCount) ?></div><div class="col-md-4"><strong>Lost:</strong> <?= e((string)$lostCount) ?></div></div></div>
<div class="row g-3"><div class="col-md-6"><div class="card"><div class="card-header">Source-wise</div><ul class="list-group list-group-flush"><?php foreach($sources as $s):?><li class="list-group-item d-flex justify-content-between"><span><?= e($s['source']) ?></span><strong><?= e((string)$s['c']) ?></strong></li><?php endforeach;?></ul></div></div><div class="col-md-6"><div class="card"><div class="card-header">Service-wise</div><ul class="list-group list-group-flush"><?php foreach($services as $s):?><li class="list-group-item d-flex justify-content-between"><span><?= e($s['service_interest']) ?></span><strong><?= e((string)$s['c']) ?></strong></li><?php endforeach;?></ul></div></div></div>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
