<?php
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/settings_helper.php';
require_login();
$rows=$pdo->query('SELECT t.title,t.due_date,t.priority,t.status,l.full_name lead_name,u.full_name assignee FROM lead_tasks t LEFT JOIN leads l ON l.id=t.lead_id LEFT JOIN users u ON u.id=t.assigned_user_id ORDER BY t.due_date ASC')->fetchAll();
$company = setting($pdo,'company_name','Startup Team');
$brand = setting($pdo,'report_branding','Lead Report');
$logo = setting($pdo,'company_logo','');
?>
<!doctype html><html><head><meta charset="utf-8"><title>Task Summary</title><style>body{font-family:Arial,sans-serif;padding:24px}.head{display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid #333;padding-bottom:10px;margin-bottom:12px}.logo{height:40px}.meta{font-size:12px;color:#555}.tbl{width:100%;border-collapse:collapse}.tbl th,.tbl td{border:1px solid #ddd;padding:7px;font-size:12px}.tbl th{background:#f4f4f4;text-align:left}.badge{padding:2px 6px;border-radius:8px;font-size:11px;color:#fff}.pending{background:#6c757d}.progress{background:#fd7e14}.done{background:#198754}.cancel{background:#343a40}</style></head><body><div class="head"><div><?php if($logo): ?><img class="logo" src="<?= htmlspecialchars(url($logo)) ?>"><?php endif; ?><h3 style="margin:4px 0 0"><?= htmlspecialchars($company) ?></h3><div class="meta"><?= htmlspecialchars($brand) ?> - Task Summary</div></div><div class="meta">Printed: <?= date('Y-m-d H:i') ?></div></div><table class="tbl"><thead><tr><th>Title</th><th>Lead</th><th>Assignee</th><th>Due</th><th>Priority</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r): $statusClass=$r['status']==='Done'?'done':($r['status']==='In Progress'?'progress':($r['status']==='Cancelled'?'cancel':'pending'));?><tr><td><?= htmlspecialchars($r['title']) ?></td><td><?= htmlspecialchars((string)$r['lead_name']) ?></td><td><?= htmlspecialchars((string)$r['assignee']) ?></td><td><?= htmlspecialchars($r['due_date']) ?></td><td><?= htmlspecialchars($r['priority']) ?></td><td><span class="badge <?= $statusClass ?>"><?= htmlspecialchars($r['status']) ?></span></td></tr><?php endforeach;?></tbody></table><script>window.print()</script></body></html>
